Not Found: /admin/config.html
Not Found: /admin/config/1
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config.html
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Not Found: /admin/config.html
Not Found: /admin/config/itens.html
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Not Found: /admin/config/recursos.html
Not Found: /admin/config/planos.html
Not Found: /admin/config/menu.html
Not Found: /admin/config/recursos.html
Not Found: /admin/config/recursos.html
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /admin/config/config.html
